config/routes.rb
Todo::Application.routes.draw do

  devise_for :users
  root to: 'lists#index'

  resources :lists do
    member do
      get 'new_list_for_user'
    end

    collection do
      put 'complete'
    end

  end

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index

      @lists_open = current_user.lists.where(complete: false)
      @lists_closed = current_user.lists.where(complete: true)
      #@lists = List.where(complete: false)
  end

  def complete
    if params[:my_tag]
      @lists = List.where(id: params[:my_tag])

      @lists.each do | list |
        list.complete = true
        list.save
      end
    end

    redirect_to lists_path
  end


  def show

  end


  def new_list_for_user
    @list = List.new(user_id: "#{params[:id]}")
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list), :notice => "Your new ToDo item was created!"
    else
      render "new"
    end

  end

  def edit

  end

  def update
    @list = @list.update(list_params)

    redirect_to lists_path
  end

 def destroy
   @list.delete

   redirect_to lists_path, :alert => "Are you sure?"
 end

  def list_params
    params.require(:list).permit(:id, :name, :remarks, :complete, :user_id)
  end

  def set_list
    @list = List.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<div id="user_nav">

      <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "btn btn-small btn-danger" %>
      <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path  %>
      <% end %>

      <%= link_to "Change your password", edit_user_registration_path, :class => "btn btn-small btn-warning" %>
</div>
<hr>

<!--login authentication-->
<% flash.each do |name, msg| %>
     <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>


<%= yield %>

</body>

</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :remarks %><br>
    <%= f.text_area :remarks %>
  </div>

  <% if @list.persisted? %>
      <div class="field">
        <%= f.label :complete %><br>
        <%= f.check_box(:complete, false)%>
      </div>
  <% end%>



    <div class="field">
      <%=   %><br>
      <%= f.hidden_field :user_id %>
  </div>


    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>


<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h4>Todo list as on <%= Time.now.strftime("%d-%m-%Y")%> </h4>

<%= form_tag complete_lists_path, method: :put do %>

<table class="table table-bordered table-hover" >
  <thead>
    <tr>
      <th>Name</th>
      <th>Remarks</th>
      <th>Created at</th>
      <th>Status</th>
      <th>ACTION</th>

    </tr>
  </thead>

  <tbody>
    <% @lists_open.each do |list| %>
      <tr>
        <td><%= list.name.titlecase %></td>
        <td><%= list.remarks.capitalize %></td>
        <td><%= list.created_at.strftime("%d-%b-%Y") %> </td>
        <td><%= check_box_tag "my_tag[]", list.id, false %> </td>

        <td><%= link_to 'Edit', edit_list_path(list), :class => "btn btn-small btn-warning" %></td>

      </tr>

        <% end %>
  </tbody>
</table>

    <%= submit_tag "Mark as Complete" %>
 <% end %>

<%= link_to 'New List', new_list_for_user_list_path(current_user.id), :class => "btn btn-small btn-success" %>
 <hr>
<h4> Completed ToDo Lists </h4>

<table class="table table-condensed table-bordered" >
  <thead>
  <tr>
    <th>Sl</th>
    <th>Name</th>
    <th>Remarks</th>
    <th>Created On</th>
    <th>Completed On</th>
    <th>ACTION</th>
  </tr>
  </thead>

  <tbody>
  <ol>          <% x = 0 %>
  <% @lists_closed.each do |list| %>
      <tr>
        <td><%= x += 1  %> </td>
        <td><%= list.name.titlecase %></td>
        <td><%= list.remarks.capitalize %></td>
        <td><%= list.created_at.strftime("%d-%b-%Y") %> </td>
        <td><%= list.updated_at.strftime("%d-%b-%Y") %> </td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small btn-danger" %></td>
      </tr>
    <% end %>
        </ol>
  </tbody>

</table>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/new_list_for_user.html.erb
<h1>New list</h1>

<%= form_for @list do |list| %>

   Name: <%= list.text_field :name %> <br>
    Remarks: <%= list.text_area :remarks %> <br>
   <%= list.hidden_field :complete, :value => "false" %> <br>
    <%= list.hidden_field :user_id %> <br>

    <%= list.submit "Create List" %>

<% end %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @list.remarks %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @list.complete %>
</p>

<%= link_to 'Edit', edit_list_path(@list), :class => "btn btn-small btn-warning" %>
<%= link_to 'Back', lists_path, :class => "btn btn-small btn-primary" %>